# Site settings
title: Meghana Marathe
email: meghanam@umich.edu
description: > # this means to ignore newlines until "baseurl:"
  I'm a PhD student in the School of Information at the University of Michigan, Ann Arbor.
  I am interested in two broad areas: computational social science and ICTD.
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://marathem.com" # the base hostname & protocol for your site
twitter_username: marathe_megh
github_username:  marathem
#permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown

# needed for CI builds:
exclude: [vendor]
